### ISSUE TITLE
Missing Device OS info

### ISSUE THREAD

**Issue by timbrand** [KSemenenko/Google-Analytics-for-Xamarin-Forms#1]
First I want to thank you for creating this project! Was waiting for it and this seems a good solution!

I've implemented it into my Xamarin.Forms app (currently only tested on iOS) and I see I'm missing the Device Info in Google Analytice, info like Device Branding, OS...

I implemented it the exact same way as your Init-code in the example.

Am I doing something wrong or is the project not sending the OS data yet?

**Comment by KSemenenko** [comment]
Hello. Thank you for trying out this project. For this code:
 
`var config = new TrackerConfig();
config.AppVersion = "1.0.0.0";
config.TrackingId = "UA-11111111-1";
config.AppId = "AppID";
config.AppName = "Google Analytics Test";
config.AppInstallerId = Guid.NewGuid().ToString();
//config.Debug = true;
TrackerFactory.Config = config;
var tracker = new TrackerFactory().GetTracker();
tracker.SendView("MainPage");` 

should work. Now there is an implementation for iOS and Android. Since the project is in the development stage it can be the case that I'd missed it. As for device type, I take UserAgent from browser and add it to request. This enables to identify a device, but doesn't work well in emulator. If you provide me with more info on what is missing, I'll add to it to the project in less time.

**Comment by timbrand** [comment]
I'll definitely going to help you on this project. Almost started my own, but didn't had the time to make it as dynamic as you did. So will bring my piece to it.

I tried that exact code.
I just enabled the Debug property and checked the response. The "hit" in the response shows the request, this one isn't showing an UserAgent (ua), see:
```json
{
  "hitParsingResult": [ {
    "valid": true,
    "parserMessage": [ ],
    "hit": "/debug/collect?v=1\u0026tid=UA-******\u0026cid=0000000u0026an=MyApp\u0026av=102\u0026t=screenview\u0026aid=com.com.myapp\u0026aiid=c9c36408-ab9e-4147-b454-38e3f8f8c2b1\u0026cd=PostFeed\u0026sc=start"
  } ],
  "parserMessage": [ {
    "messageType": "INFO",
    "description": "Found 1 hit in the request."
  } ]
}
(replaced some private values)
```
I guess the 'ua' should be in that request too.

Is the project PCL compatible? As I'm currently using it in a PCL project.

**Comment by KSemenenko** [comment]
yes, it is PCL compatible.

**Comment by timbrand** [comment]
I've used the iOS test app and noticed the missing ua-parameter too. Created a possible fix, PullRequest #3

**Comment by KSemenenko** [comment]
Thanks a lot!

**Comment by timbrand** [comment]
I can confirm the fix now. I'm seeing the device details in my GA now (there's some delay before that information is visible).
Could you submit a new NuGet?

**Comment by KSemenenko** [comment]
NuGet update :)

**Comment by KSemenenko** [comment]
Hello, I've updated the code a little. I'd like to know your opinion if it is more convenient now.

[issues](https://github.com/KSemenenko/Google-Analytics-for-Xamarin-Forms/issues/4)
[branch](https://github.com/KSemenenko/Google-Analytics-for-Xamarin-Forms/tree/XamarinPlugin)

**Comment by farax** [comment]
Hi, 

Just on this topic, I am also using the init example you have got (Xamarin forms) and cannot seem to get the device details. Anything I am missing there?

**Comment by KSemenenko** [comment]
Use the initialization in the same place where Xamarin Forms is initialized.
Or somewhere in App.cs
And what is your device?
```cs
GoogleAnalytics.Current.Config.TrackingId = "UA-11111111-1";
GoogleAnalytics.Current.Config.AppId = "AppID";
GoogleAnalytics.Current.Config.AppName = "TEST";
GoogleAnalytics.Current.Config.AppVersion = "1.0.0.0";
GoogleAnalytics.Current.InitTracker();
```

**Comment by farax** [comment]
Ah yes. I had the code in the right place .... I think this data took a few hours to come through. Now it is showing the devices. Thanks for the great package! 👍
